/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package rheeluke.streams.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Hashtag extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7047101981464705557L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Hashtag\",\"namespace\":\"rheeluke.streams.avro\",\"fields\":[{\"name\":\"text\",\"type\":\"string\"}],\"connect.name\":\"rheeluke.streams.avro.Hashtag\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence text;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Hashtag() {}

  /**
   * All-args constructor.
   * @param text The new value for text
   */
  public Hashtag(java.lang.CharSequence text) {
    this.text = text;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return text;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: text = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'text' field.
   * @return The value of the 'text' field.
   */
  public java.lang.CharSequence getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.CharSequence value) {
    this.text = value;
  }

  /**
   * Creates a new Hashtag RecordBuilder.
   * @return A new Hashtag RecordBuilder
   */
  public static rheeluke.streams.avro.Hashtag.Builder newBuilder() {
    return new rheeluke.streams.avro.Hashtag.Builder();
  }

  /**
   * Creates a new Hashtag RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Hashtag RecordBuilder
   */
  public static rheeluke.streams.avro.Hashtag.Builder newBuilder(rheeluke.streams.avro.Hashtag.Builder other) {
    return new rheeluke.streams.avro.Hashtag.Builder(other);
  }

  /**
   * Creates a new Hashtag RecordBuilder by copying an existing Hashtag instance.
   * @param other The existing instance to copy.
   * @return A new Hashtag RecordBuilder
   */
  public static rheeluke.streams.avro.Hashtag.Builder newBuilder(rheeluke.streams.avro.Hashtag other) {
    return new rheeluke.streams.avro.Hashtag.Builder(other);
  }

  /**
   * RecordBuilder for Hashtag instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Hashtag>
    implements org.apache.avro.data.RecordBuilder<Hashtag> {

    private java.lang.CharSequence text;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(rheeluke.streams.avro.Hashtag.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.text)) {
        this.text = data().deepCopy(fields()[0].schema(), other.text);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Hashtag instance
     * @param other The existing instance to copy.
     */
    private Builder(rheeluke.streams.avro.Hashtag other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.text)) {
        this.text = data().deepCopy(fields()[0].schema(), other.text);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'text' field.
      * @return The value.
      */
    public java.lang.CharSequence getText() {
      return text;
    }

    /**
      * Sets the value of the 'text' field.
      * @param value The value of 'text'.
      * @return This builder.
      */
    public rheeluke.streams.avro.Hashtag.Builder setText(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.text = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'text' field has been set.
      * @return True if the 'text' field has been set, false otherwise.
      */
    public boolean hasText() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'text' field.
      * @return This builder.
      */
    public rheeluke.streams.avro.Hashtag.Builder clearText() {
      text = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Hashtag build() {
      try {
        Hashtag record = new Hashtag();
        record.text = fieldSetFlags()[0] ? this.text : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
