# The port on which the Pivot server will listen on.
port: 9090

clusters:
  - name: druid
    type: druid

    # A Druid broker node that can serve data (only used if you have Druid based data source)
    host: ec2-54-71-20-46.us-west-2.compute.amazonaws.com:8082
    sourceListScan: auto
    sourceListRefreshInterval: 15000

    # Background introspection frequency (in ms)
    # - Set to '0' to disable background introspection.

    # Foreground introspection
    # Checks for new dataSources every time Pivot is loaded (default: false)
    sourceListRefreshOnLoad: false

# Data source definitions will go here
dataSources: []
